import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Micro app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>This is the micro app</h1>

        <a href="http://localhost:3000" className={styles.card}>
          <h2>Host app &rarr;</h2>
          <p>Click to navigate to the host app</p>
        </a>
      </main>
    </div>
  );
}
